extends GutTest
## Pins SimRng's output so fights replay identically across Godot versions.


func test_matches_published_xoshiro128starstar_vector() -> void:
	# Reference output for state {1, 2, 3, 4} from the xoshiro128** reference code.
	var rng := SimRng.new(0)
	rng.set_state(1, 2, 3, 4)
	var values: Array[int] = []
	for i: int in 6:
		values.append(rng.next_u32())
	assert_eq(values, [11520, 0, 5927040, 70819200, 2031721883, 1637235492] as Array[int])


func test_seeded_output_is_pinned() -> void:
	# Generated by a Python reference of the same seeding (see sim_rng.gd).
	var expected: Dictionary[int, Array] = {
		1: [1582369674, 2167066320, 2410384964, 1791316217, 2575855357],
		42: [2996000486, 2237303598, 1161035131, 1780366372, 2632481447],
		123456789012: [2241739978, 2073185756, 76196594, 1949981822, 1974891629],
	}
	for seed_value: int in [1, 42, 123456789012]:
		var rng := SimRng.new(seed_value)
		var values: Array = []
		for i: int in 5:
			values.append(rng.next_u32())
		assert_eq(values, expected[seed_value], "seed %d" % seed_value)


func test_range_int_stays_in_range_and_covers_it() -> void:
	var rng := SimRng.new(7)
	var seen: Array[bool] = [false, false, false, false, false, false]
	for i: int in 600:
		var value: int = rng.range_int(6)
		assert_between(value, 0, 5)
		seen[value] = true
	assert_eq(seen, [true, true, true, true, true, true] as Array[bool])


func test_roll_bp_edges_use_no_randomness() -> void:
	var a := SimRng.new(3)
	var b := SimRng.new(3)
	assert_false(a.roll_bp(0))
	assert_true(a.roll_bp(FixedMath.BP_ONE))
	assert_eq(a.next_u32(), b.next_u32(), "0% and 100% rolls don't advance the generator")


func test_roll_bp_rate_is_roughly_right() -> void:
	var rng := SimRng.new(11)
	var hits: int = 0
	for i: int in 10000:
		if rng.roll_bp(2500):
			hits += 1
	assert_between(hits, 2300, 2700, "about 25%")
